import { theme } from "../../theme";

const iconPath = "assets/icons";
const imagePath = "assets/images";

export const IconPath = {
  star1: `${iconPath}/star1.svg`,
  star2: `${iconPath}/star2.svg`,
  switch: `${iconPath}/switch.svg`,
};

export const ImagePath = {
  rectangle1: `${imagePath}/Rectangle1.svg`,
  rectangle2: `${imagePath}/Rectangle2.svg`,
  rectangle3: `${imagePath}/Rectangle3.svg`,
  rectangle4: `${imagePath}/Rectangle4.svg`,
  rectangle5: `${imagePath}/Rectangle5.svg`,
  rectangle6: `${imagePath}/Rectangle6.svg`,
  rectangle7: `${imagePath}/Rectangle7.svg`,
  rectangle8: `${imagePath}/Rectangle8.svg`,
  rectangle9: `${imagePath}/Rectangle9.svg`,
};

export const TABS = [
  { id: 0, label: "All Assets" },
  { id: 1, label: "Watchlist" },
] as const;

export const HEADERS = [
  {
    id: 1,
    text: "Name",
    variant: "caption" as const,
    width: "300px",
    height: "42px",
  },
  {
    id: 2,
    text: "Price",
    variant: "caption" as const,
    width: "337px",
    height: "42px",
  },
  {
    id: 3,
    text: "Change",
    variant: "caption" as const,
    width: "238px",
    height: "42px",
  },
  {
    id: 4,
    text: "Market Cap",
    variant: "caption" as const,
    icon: IconPath.switch,
    width: "238px",
    height: "42px",
  },
  {
    id: 5,
    text: "Watch",
    variant: "caption" as const,
    width: "78px",
    height: "42px",
  },
];

export const DATA = [
  {
    id: 1,
    image: ImagePath.rectangle1,
    mainText: "Bitcoin",
    mainColor: theme.palette.primary.dark,
    mainVarinat: "body1" as const,
    subText: "BTC",
    subColor: theme.palette.primary.light,
    subVarinat: "overline" as const,
    price: "$3,285,553.73",
    change: "+1.06%",
    market: "$60.1T",
  },
  {
    id: 2,
    image: ImagePath.rectangle2,
    mainText: "Ethereum",
    mainColor: theme.palette.primary.dark,
    mainVarinat: "body1" as const,
    subText: "ETH",
    subColor: theme.palette.primary.light,
    subVarinat: "overline" as const,
    price: "$216,678.10",
    change: "-5.49%",
    market: "$25.4T",
  },
  {
    id: 3,
    image: ImagePath.rectangle3,
    mainText: "Ethereum 2",
    mainColor: theme.palette.primary.dark,
    mainVarinat: "body1" as const,
    subText: "ETH2",
    subColor: theme.palette.primary.light,
    subVarinat: "overline" as const,
    price: "$216,678.10",
    change: "-5.49%",
    market: "$25.4T",
  },
  {
    id: 4,
    image: ImagePath.rectangle4,
    mainText: "Tether",
    mainColor: theme.palette.primary.dark,
    mainVarinat: "body1" as const,
    subText: "USDT",
    subColor: theme.palette.primary.light,
    subVarinat: "overline" as const,
    price: "$74.31",
    change: "+0.11%",
    market: "$4.6T",
  },
  {
    id: 5,
    image: ImagePath.rectangle5,
    mainText: "Bitcoin Coin",
    mainColor: theme.palette.primary.dark,
    mainVarinat: "body1" as const,
    subText: "BNB",
    subColor: theme.palette.primary.light,
    subVarinat: "overline" as const,
    price: "$24,942.54",
    change: "-3.69%",
    market: "$4.2T",
  },
  {
    id: 6,
    image: ImagePath.rectangle6,
    mainText: "Cardano",
    mainColor: theme.palette.primary.dark,
    mainVarinat: "body1" as const,
    subText: "ADA",
    subColor: theme.palette.primary.light,
    subVarinat: "overline" as const,
    price: "$104.52",
    change: "-1.82%",
    market: "$3.4T",
  },
  {
    id: 7,
    image: ImagePath.rectangle7,
    mainText: "XRP",
    mainColor: theme.palette.primary.dark,
    mainVarinat: "body1" as const,
    subText: "XRP",
    subColor: theme.palette.primary.light,
    subVarinat: "overline" as const,
    price: "$57.21",
    change: "+1.11%",
    market: "$2.7T",
  },
  {
    id: 8,
    image: ImagePath.rectangle8,
    mainText: "Dodge Coin",
    mainColor: theme.palette.primary.dark,
    mainVarinat: "body1" as const,
    subText: "XRP",
    subColor: theme.palette.primary.light,
    subVarinat: "overline" as const,
    price: "$17.64",
    change: "-6.96%",
    market: "$2.3T",
  },
  {
    id: 9,
    image: ImagePath.rectangle9,
    mainText: "USD Coin",
    mainColor: theme.palette.primary.dark,
    mainVarinat: "body1" as const,
    subText: "XRP",
    subColor: theme.palette.primary.light,
    subVarinat: "overline" as const,
    price: "$74.26",
    change: "+1.01%",
    market: "$2.1T",
  },
];
